class GameStatus:
    WAIT_FOR_ROLLING_DICE = 0
    ROLLING_DICE = 1
    WALK_PLAYER_TOKEN = 2
    WAIT_FOR_TRANSACTIONS = 10
    SELLING = 11
    MORTGAGING = 12
    PROP_TARGET_SELECTION = 13
    SHOWING_EVENT_CARD = 14
    SHOWING_RANDOM_EVENT_CARD = 15
    